### ISSUE TITLE
Crash on Laser Test

### ISSUE THREAD

**Issue by tickelton** [LaserWeb/lw.comm-server#113]
I'm running the latest master version 8515cfd4d51ace80a0b76a640ebd4abb7f963713 with a Sculpfun S9 with GRBL 1.1h.

When executing a Laser Test lw.comm-server crashes with the following error message:

```
laserTest: Power 3, Duration 0, maxS 1000                                                                   
laserTest: Power off                                 
/home/mint/src/lw.comm-server/server.js:3141                                                                
                appSocket.emit('laserTest', 0);                                                             
                ^

ReferenceError: appSocket is not defined
    at laserTest (/home/mint/src/lw.comm-server/server.js:3141:17)
    at Socket.<anonymous> (/home/mint/src/lw.comm-server/server.js:2015:9)
    at Socket.emit (events.js:314:20)
    at Socket.emitUntyped (/home/mint/src/lw.comm-server/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/mint/src/lw.comm-server/node_modules/socket.io/dist/socket.js:703:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    ```

**Comment by cprezzi** [comment]
Oh. That is a bug. The command on line 3141 should be `io.sockets.emit('laserTest', 0);` not appSocket...
